// <auto-generated />
namespace BrewHow.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RecipeValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecipeValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201306250424487_RecipeValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
